import fs from 'node:fs';
import {compileMicroCore} from '../src/micro-core.ts';
import {PackedMicroRuntime,writeMicroPlan,type MicroPlan} from '../src/packed-micro.ts';
import assert from 'node:assert/strict';
import { keccak256,encodeAbiParameters,parseAbiParameters,type Abi,type Address,type Hex } from 'viem';
import { indexedLeaf,ZERO } from '../src/merkle.ts';
import { V3_SLOT_ABI } from '../src/merkle.ts';
import { IncrementalMerkle } from '../src/incremental-merkle.ts';
import { unpack } from '../src/netlist.ts';
import { hash } from '../src/model.ts';
import { openArchive } from '../src/archive.ts';
/** Scalable chain execution extractor. One 512-byte connection chunk is live at a time.
 * Slot permutation is explicit: arbitrary chain module groups become contiguous local state ranges.
 * Independent provenance remains in the authenticated archive; no original blueprint is an argument.
 */
export async function reconstructPackedMicroChain(read:(a:Address,abi:Abi,fn:string,args?:any[])=>Promise<any>,brain:Address,abi:Abi,cpuAbi:Abi,destination:string,trusted:{slotRoot:Hex;dataRoot:Hex;frameRoot:Hex;checkpointHash:Hex;microcheckpointHash:Hex;verifyBlock:()=>Promise<void>}){
 const out=destination+'.partial';if(fs.existsSync(destination))throw Error('FRESH_RECONSTRUCTION_REQUIRED');
 const start=performance.now(),cfg=await read(brain,abi,'config'),cpu=await read(brain,abi,'collection'),limits={maxNeurons:1000000,maxSlots:1048576,maxEdges:50000000,maxArchiveBytes:64*1024*1024,maxMs:600000,maxRequests:2000000};let requests=2;
 if(cfg[6]!==trusted.slotRoot||cfg[7]!==trusted.dataRoot||cfg[8]!==trusted.frameRoot||await read(brain,abi,'checkpointHash')!==trusted.checkpointHash||await read(brain,abi,'microcheckpointHash')!==trusted.microcheckpointHash)throw Error('TRUSTED_CHAIN_ANCHOR');
 if(cfg[0]>limits.maxSlots||cfg[1]>limits.maxNeurons||cfg[4]*8192>limits.maxArchiveBytes)throw Error('PACKED_CHAIN_BUDGET');if(fs.existsSync(out)&&fs.readdirSync(out).length)throw Error('EMPTY_OUTPUT_REQUIRED');fs.mkdirSync(out,{recursive:true});
 const fetch=async(fn:string,args:any[]=[])=>{if(++requests>limits.maxRequests||performance.now()-start>limits.maxMs)throw Error('PACKED_CHAIN_BUDGET');return read(brain,abi,fn,args);};
 const archiveFile=out+'/metadata.fbc',archiveFd=fs.openSync(archiveFile,'wx'),archiveTree=new IncrementalMerkle();let metadataBytes=0;try{for(let i=0;i<cfg[4];i++){const hex=await fetch('dataChunk',[BigInt(i)]),chunk=Buffer.from(hex.slice(2),'hex');if(chunk.length>8192)throw Error('PACKED_CHAIN_CHUNK');archiveTree.append(indexedLeaf(i,keccak256(hex)));fs.writeSync(archiveFd,chunk);metadataBytes+=chunk.length;}}finally{fs.closeSync(archiveFd);}assert.equal(archiveTree.finish(),cfg[7]);
 const probe=Buffer.alloc(4),probeFd=fs.openSync(archiveFile,'r');try{fs.readSync(probeFd,probe);}finally{fs.closeSync(probeFd);}
 let metadata:any;
 if(probe.toString()==='FBD1'){
  const archive=openArchive(archiveFile),m=archive.header.metadata,ids=archive.section('ids');if(ids.length!==cfg[1]*8)throw Error('PACKED_CHAIN_IDS');for(const section of archive.header.sections)if(section.name!=='ids')archive.section(section.name);
  // FBD1 canonical JSON sorts keys. Validate all values before restoring legacy hash order.
  assert.deepEqual(m.core,compileMicroCore());
  metadata={core:m.core,ids:Array.from({length:cfg[1]},(_,i)=>ids.readBigUInt64LE(i*8).toString()),source:{classification:m.classification,data:m.source,policy:m.profile,formalUnresolvedGlobal:m.parameters?.unresolved??0}};
 }else {throw Error('MALECNS_ARCHIVE_REQUIRED');}assert.equal(metadata.ids.length,cfg[1]);
 const n=cfg[1],modules=cfg[0],specs:any[]=[],moduleOffsets=new Uint32Array(modules+1),packedToOriginal=new Uint32Array(n),originalToPacked=new Int32Array(n).fill(-1),offsets=new Uint32Array(n+1),thresholds=new Uint16Array(n),initialV=new Int16Array(n),initialSpikes=new Uint8Array(n),slotTree=new IncrementalMerkle();let count=0;
 for(let slot=0;slot<modules;slot++){const spec=await fetch('slotSpec',[BigInt(slot)]);if(spec.neurons.length<1||spec.neurons.length>16||spec.edgeCounts.length!==spec.neurons.length||spec.thresholds.length!==spec.neurons.length)throw Error('PACKED_CHAIN_SLOT');slotTree.append(indexedLeaf(slot,keccak256(encodeAbiParameters(V3_SLOT_ABI,[spec]))));const initial=unpack(spec.initialState,spec.neurons.length*17);specs.push(spec);
  for(let j=0;j<spec.neurons.length;j++){const original=spec.neurons[j];if(original>=n||originalToPacked[original]!==-1||count>=n)throw Error('PACKED_CHAIN_MAPPING');packedToOriginal[count]=original;originalToPacked[original]=count;thresholds[count]=spec.thresholds[j];offsets[count+1]=offsets[count]+spec.edgeCounts[j];let v=0;for(let b=0;b<16;b++)v|=initial[j*17+b]<<b;initialV[count]=v;initialSpikes[count]=initial[j*17+16];count++;}moduleOffsets[slot+1]=count;
 }assert.equal(count,n);assert.equal(slotTree.finish(),cfg[6]);if(offsets[n]>limits.maxEdges)throw Error('PACKED_CHAIN_EDGE_BUDGET');
 const sources=new Uint32Array(offsets[n]),weights=new Int16Array(offsets[n]);let netlist:Hex|undefined;
 for(let slot=0;slot<modules;slot++){const spec=specs[slot],holding=await fetch('holding',[BigInt(slot)]);assert.notEqual(holding.depositor,'0x0000000000000000000000000000000000000000');const actual=await read(cpu,cpuAbi,'netlist',[holding.tokenId]);requests++;assert.equal(keccak256(actual),spec.netlistHash);if(netlist)assert.equal(actual,netlist);else netlist=actual;assert.equal(hash(actual),metadata.core.netlistHash);assert.deepEqual(await read(cpu,cpuAbi,'circuitInfo',[holding.tokenId]),[12,3,3,59]);requests++;
  const first=moduleOffsets[slot],end=moduleOffsets[slot+1],records=offsets[end]-offsets[first],edgeTree=new IncrementalMerkle();let target=first;
  for(let block=0;block<Math.ceil(records/64);block++){const hex=await fetch('edgeChunk',[BigInt(slot),BigInt(block)]),chunk=Buffer.from(hex.slice(2),'hex');assert.equal(chunk.length,Math.min(64,records-block*64)*8);edgeTree.append(indexedLeaf(block,keccak256(hex)));for(let b=0;b<chunk.length;b+=8){const edge=offsets[first]+block*64+b/8;while(target<end&&edge>=offsets[target+1])target++;if(target===end||chunk.readUInt16LE(b+4)!==target-first)throw Error('PACKED_CHAIN_EDGE_TARGET');const original=chunk.readUInt32LE(b);if(original<0x80000000){if(original>=n||originalToPacked[original]<0)throw Error('PACKED_CHAIN_SOURCE');sources[edge]=originalToPacked[original];}else sources[edge]=original;weights[edge]=chunk.readInt16LE(b+6);}}assert.equal(edgeTree.finish(),spec.edgeRoot);
 }
 const frameTree=new IncrementalMerkle(),frames:Uint8Array[]=[];for(let i=0;i<cfg[3];i++){const hex=await fetch('inputFrame',[BigInt(i)]);frameTree.append(indexedLeaf(i,keccak256(hex)));frames.push(Uint8Array.from(unpack(hex,cfg[2])));}assert.equal(frameTree.finish(),cfg[8]);
 const plan:MicroPlan={core:{...metadata.core,netlist:netlist!},offsets,sources,weights,thresholds,moduleOffsets,frames,initialV,initialSpikes,classification:metadata.source.classification};
 const written=writeMicroPlan(out+'/execution',plan,{chainConfig:cfg,ids:metadata.ids,packedToOriginal:Array.from(packedToOriginal),sourceArchive:'../metadata.fbc',source:metadata.source.data,policy:metadata.source.policy,formalUnresolvedGlobal:metadata.source.formalUnresolvedGlobal});
 const rt=new PackedMicroRuntime(plan,written.digest),checkpoint=rt.snapshot();checkpoint.metadata.step=Number(await fetch('completedSteps'));checkpoint.metadata.round=Number(await fetch('roundNonce'));checkpoint.metadata.version=Number(await fetch('assemblyVersion'));checkpoint.metadata.active=await fetch('active');checkpoint.metadata.completed=Number(await fetch('completedModules'));
 const stateTree=new IncrementalMerkle(),workTree=new IncrementalMerkle();for(let slot=0;slot<modules;slot++){const state=await fetch('committedState',[BigInt(slot)]),pending=await fetch('pendingState',[BigInt(slot)]),w=await fetch('currentWork',[BigInt(slot)]),first=moduleOffsets[slot],size=moduleOffsets[slot+1]-first;stateTree.append(indexedLeaf(slot,keccak256(state)));if(checkpoint.metadata.active&&Number(w.round)!==checkpoint.metadata.round)throw Error('PACKED_CHAIN_WORK_ROUND');workTree.append(Number(w.round)!==checkpoint.metadata.round||w.cycles===0?ZERO:keccak256(encodeAbiParameters(parseAbiParameters('uint256,uint64,uint32,uint32,uint32,uint8,uint8,uint32,bytes32'),[BigInt(slot),BigInt(w.round),w.neuron,w.cursor,w.cycles,w.bitIndex,w.phase,w.bits,keccak256(pending)])));for(const [hex,v,spikes] of [[state,checkpoint.arrays.v,checkpoint.arrays.spikes],[pending,checkpoint.arrays.pendingV,checkpoint.arrays.pendingSpikes]] as const){const bits=unpack(hex,size*17);for(let j=0;j<size;j++){let value=0;for(let b=0;b<16;b++)value|=bits[j*17+b]<<b;v[first+j]=value;spikes[first+j]=bits[j*17+16];}}checkpoint.arrays.neuron[slot]=first+w.neuron;checkpoint.arrays.cursor[slot]=w.cursor;checkpoint.arrays.phase[slot]=w.phase;checkpoint.arrays.cycles[slot]=w.cycles;checkpoint.arrays.bit[slot]=w.bitIndex;checkpoint.arrays.acc[slot]=w.bits>>>3;checkpoint.arrays.states.set([w.bits&1,(w.bits>>>1)&1,(w.bits>>>2)&1],slot*3);checkpoint.arrays.workRound[slot]=w.cycles?Number(w.round):0;}
 assert.equal(stateTree.finish(),await fetch('stateRoot'));if(checkpoint.metadata.active)assert.equal(workTree.finish(),await fetch('workRoot'));const stateDigest=rt.digest(checkpoint);rt.restore(checkpoint,stateDigest);const cp=rt.save(out+'/checkpoint');await trusted.verifyBlock();assert.equal(await fetch('checkpointHash'),trusted.checkpointHash);assert.equal(await fetch('microcheckpointHash'),trusted.microcheckpointHash);
 const result={status:'PASS',slots:modules,neurons:n,records:sources.length,connectionBytesOnChain:sources.length*8,executionBytes:written.bytes,metadataBytes,requests,elapsedMs:performance.now()-start,peakRssBytes:process.resourceUsage().maxRSS*1024,replayHistoryCycles:0,limits,executionDigest:written.digest,checkpointDigest:cp.digest,readChunkBytes:512,merkleMemory:'O(log chunks/slots)',activeCheckpoint:'Logical and partial work roots verified incrementally; no history replay'};fs.writeFileSync(out+'/reconstruction.json',JSON.stringify({...result,stateDigest,anchor:{...trusted,verifyBlock:undefined}},null,2)+'\n');fs.renameSync(out,destination);return {result,plan,checkpoint};
}