import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {sourceIdentity} from '../src/source-identity.ts';
import {prepare} from '../src/initial.ts';import {readJSON,atomic,digest} from '../src/integrity.ts';
import {localCheckpointPath,saveLocalCheckpoint} from '../src/t2-local-checkpoint.ts';import {reference,compareState} from '../src/reference.ts';
const arg=(s:string)=>{const i=process.argv.indexOf(s);return i<0?undefined:process.argv[i+1];};
const steps=Number(arg('--steps')??2);assert.equal(steps,2,'RELEASE_HAS_TWO_FRAMES');const wall=performance.now();const {loaded,rt,release}=await prepare();const provenance=loaded.provenance as any;
const resume=arg('--resume'),out=arg('--out')??'results/run-'+Date.now();assert.ok(path.resolve(out).startsWith(path.resolve('results')+path.sep),'OUTPUT_MUST_BE_UNDER_RESULTS');assert.ok(!fs.existsSync(out),'FRESH_OUTPUT_REQUIRED');fs.mkdirSync(out,{recursive:true});
let previous:any,priorSteps:any[]=[];if(resume){assert.ok(path.resolve(resume).startsWith(path.resolve('results')+path.sep),'RESUME_MUST_BE_UNDER_RESULTS');previous=readJSON(resume);const {reportDigest,...body}=previous;assert.equal(digest(body),reportDigest,'LOCAL_REPORT_CHANGED');assert.equal(previous.exportDigest,release.exportDigest);assert.equal(previous.planDigest,loaded.digest);assert.notEqual(previous.pid,process.pid,'INDEPENDENT_PROCESS_REQUIRED');rt.load(localCheckpointPath(path.join(path.dirname(resume),'checkpoint'),previous.checkpoint),previous.checkpoint.digest,previous.checkpoint.stateDigest);priorSteps=previous.steps;}
const expected=readJSON('expected/steps.json').steps;let refV=rt.v.slice(),refS=rt.spikes.slice(),ops=0;const start=performance.now();let records=[...priorSteps],partial=false,nextLog=50000000;
while(rt.step<steps){if(!rt.active)rt.begin();const began=performance.now();for(let j=0;j<rt.modules;j++){const slot=rt.step%2?j:rt.modules-1-j;while(!rt.done(slot)){const n=Math.min(65536,rt.remaining(slot));rt.advance(slot,n);ops+=n;if(ops>=nextLog){console.log(JSON.stringify({event:'gate-progress',step:rt.step+1,completedModules:rt.completed,totalModules:rt.modules,operations:ops,elapsedMs:performance.now()-start}));nextLog+=50000000;}
 if((process.argv.includes('--save-partial-and-exit')&&ops>=70001)||performance.now()-start>600000||process.memoryUsage().rss>1610612736){partial=true;break;}}
 if(partial)break;}if(partial)break;rt.commit();const ref=reference(loaded.plan,refV,refS,loaded.plan.frames[rt.step-1]);const fd=fs.openSync(out+'/step'+rt.step+'.states.txt','wx');let result;try{result=compareState(rt,ref,provenance.ids,provenance.packedToOriginal,s=>fs.writeSync(fd,s));}finally{fs.closeSync(fd);}assert.equal(result.bodyStateSha256,expected[rt.step-1].bodyStateSha256,'PUBLISHED_STATE_HASH');assert.equal(result.spikes,expected[rt.step-1].spikes,'PUBLISHED_SPIKES');refV=ref.v;refS=ref.spikes;const record={step:rt.step,...result,elapsedMs:performance.now()-began};records.push(record);console.log(JSON.stringify(record));}
rt.audit();const checkpoint=saveLocalCheckpoint(rt,out+'/checkpoint');const report={schema:'droso-local-run-v1',status:partial?'PARTIAL':'PASS_TWO_LOCAL_STEPS',exportDigest:release.exportDigest,planDigest:loaded.digest,pid:process.pid,initialStep:previous?.completedSteps??0,completedSteps:rt.step,active:rt.active,steps:records,checkpoint,resumedFrom:resume??null,independentProcessPartialRestore:!!previous&&previous.active,operations:ops,runMs:performance.now()-start,totalMs:performance.now()-wall,peakRssBytes:process.resourceUsage().maxRSS*1024,sourceDigest:sourceIdentity().digest,networkIsolation:(globalThis as any).__drosoNetworkGuard??{mode:'NOT_INSTRUMENTED'},networkRequests:(globalThis as any).__drosoNetworkGuard?.attempts??null,publicTransactions:0,durability:process.permission?'ATOMIC_HASH_VALIDATED_SANDBOX_FSYNC_UNAVAILABLE':'FSYNC_ATOMIC',machine:{node:process.version,platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model,cores:os.cpus().length,totalMemory:os.totalmem()}};atomic(out+'/report.json',{...report,reportDigest:digest(report)});console.log(JSON.stringify({status:report.status,report:out+'/report.json',runMs:report.runMs}));
