import fs from 'node:fs';import assert from 'node:assert/strict';import {decodeFunctionResult} from 'viem';
import {snapshot} from '../src/initial.ts';import {httpRpc,anchor,historicalTag,identity,call,verifySlot,verifyPage,sampleIndices,Unavailable} from '../src/chain.ts';import {readJSON,atomic,digest} from '../src/integrity.ts';import {ba} from '../src/abi.ts';
const arg=(s:string)=>{const i=process.argv.indexOf(s);return i<0?undefined:process.argv[i+1];};
async function main(){const out=arg('--out')??'results/chain-'+Date.now()+'.json';assert.ok(/^results\/[a-zA-Z0-9_./-]+\.json$/.test(out)&&!out.includes('..'),'OUTPUT_PATH');const status=process.argv.includes('--status'),mode=arg('--mode')??'sample';assert.ok(['full','sample'].includes(mode));let url=process.env.BSC_TESTNET_RPC_URL;
 if(!url&&fs.existsSync('.env')){const m=/^BSC_TESTNET_RPC_URL\s*=\s*["']?([^\r\n"']+)/m.exec(fs.readFileSync('.env','utf8'));url=m?.[1].trim();}
 if(!url){const r={status:'NOT_RUN',reason:'RPC_NOT_CONFIGURED',mode:status?'current-status':mode};atomic(out,r);console.log(JSON.stringify(r));return;}
 const {request:rpc,count}=httpRpc(url),started=Date.now();let progress:any={mode,slots:0,pages:0};
 try{if(status){assert.equal(await rpc('eth_chainId'),'0x61','WRONG_CHAIN');const b=await rpc('eth_getBlockByNumber',['latest',false]),a=readJSON('deployments/bsc-testnet/deployment.json').addresses,values:any={};for(const fn of ['ready','presentCount','assemblyVersion','completedSteps','active','isSealed','custodyFault','implementationValid'])values[fn]=decodeFunctionResult({abi:ba,functionName:fn,data:await call(rpc,b.number,a.brain,ba,fn)});await anchor(rpc,b);const r={status:'CURRENT_STATE_OBSERVED',block:{number:b.number,hash:b.hash},at:new Date().toISOString(),values,rpc:count(),historicalSnapshotInvalidated:false};atomic(out,r);console.log(JSON.stringify(r,(_,x)=>typeof x==='bigint'?x.toString():x));return;}
 const {release,snap}=await snapshot(),b=release.binding.block;await anchor(rpc,b);const tag=await historicalTag(rpc,b,release.binding.brain);const a=await identity(rpc,tag);for(const [key,expected]of Object.entries(snap.manifest.globals)){const [fn,index]=key.split('/');assert.equal(await call(rpc,tag,a.brain,ba,fn,index===undefined?[]:[BigInt(index)]),expected,'GLOBAL_'+key);}
 const seed='droso-history-v1',slots=mode==='full'?Array.from({length:10419},(_,i)=>i):sampleIndices(10419,32,seed),pages=mode==='full'?Array.from({length:51567},(_,i)=>i):sampleIndices(51567,32,seed),binding=digest({export:release.exportDigest,block:b,mode,slots,pages});
 const resume=arg('--resume');if(resume){assert.ok(resume.startsWith('results/')&&!resume.includes('..'));const prior=readJSON(resume),{localDigest,...body}=prior;assert.equal(digest(body),localDigest,'RESUME_CHANGED');assert.equal(prior.binding,binding);assert.equal(prior.block.hash,b.hash);progress={...prior};}
 progress={...progress,binding,block:b,blockSelector:tag,sampling:mode==='sample'?{seed,slots,pages}:null,trust:'RPC plus publisher snapshot; no independent BSC consensus or state-proof validation. Resume trusts locally retained checkpoint; delete it for fresh audit.'};
 const save=(state:string)=>{const {localDigest,...body}=progress;const r={...body,status:state,rpcThisInvocation:count(),elapsedMs:Date.now()-started};atomic(out+'.checkpoint.json',{...r,localDigest:digest(r)});atomic(out,{...r,localDigest:digest(r)});};
 for(const [kind,indices,verify]of [['slots',slots,verifySlot],['pages',pages,verifyPage]] as const){for(let i=progress[kind];i<indices.length;i+=8){if(Date.now()-started>600000||fs.existsSync('results/STOP')){save('PARTIAL');console.log(JSON.stringify({status:'PARTIAL',resume:out+'.checkpoint.json',...progress}));return;}await anchor(rpc,b);const settled=await Promise.allSettled(indices.slice(i,i+8).map(index=>verify(rpc,tag,a,snap.get(kind,index))));for(const r of settled)if(r.status==='rejected')throw r.reason;await anchor(rpc,b);progress[kind]=Math.min(i+8,indices.length);save('PARTIAL');console.log(JSON.stringify({mode,slots:progress.slots,pages:progress.pages,rpc:count()}));}}
 await anchor(rpc,b);save(mode==='full'?'PASS_FULL_HISTORICAL_RPC_COMPARE':'PASS_SAMPLE_HISTORICAL_RPC_COMPARE');console.log(JSON.stringify({status:mode==='full'?'PASS_FULL_HISTORICAL_RPC_COMPARE':'PASS_SAMPLE_HISTORICAL_RPC_COMPARE',report:out,rpc:count()}));
 }catch(e){const r={...progress,status:e instanceof Unavailable?'UNAVAILABLE':'FAILED',reason:e instanceof Unavailable?'RPC cannot supply requested data; no latest fallback.':e instanceof Error?e.message.split('\n')[0]:'CHECK_FAILED',rpc:count(),elapsedMs:Date.now()-started};atomic(out,r);console.log(JSON.stringify(r));process.exitCode=e instanceof Unavailable?2:1;}}
main().catch(()=>{console.error('CHAIN_CHECK_FAILED');process.exitCode=1;});
