import fs from 'node:fs';
import assert from 'node:assert/strict';
import {decodeFunctionResult,toHex,keccak256,verifyMessage,encodeAbiParameters,parseAbiParameters} from 'viem';
import {initialSnapshot} from './bundle.ts';
import {T2Snapshot} from './snapshot.ts';
import {ba,ca} from './abi.ts';
import {digest,readJSON,atomic} from './integrity.ts';
import {IncrementalMerkle} from './incremental-merkle.ts';
import {compileMicroCore} from './micro-core.ts';
import {reconstructPackedMicroChain} from '../scripts/reconstruct.ts';
import {loadMicroPlan,PackedMicroRuntime} from './packed-micro.ts';
const decode=(abi:any,fn:string,x:any):any=>decodeFunctionResult({abi,functionName:fn,data:x});
export async function snapshot(){const {release,manifest,root}=initialSnapshot();
 for(const [file,kind]of [['ready.json','t2-ready'],['rebuild-report.json','t2-rebuild'],['local-acceptance-signed.json','t2-local']]){const r=readJSON('deployments/bsc-testnet/'+file);assert.ok(await verifyMessage({address:release.publisher,message:'tapeout-fly/T1/chain97/'+kind+'/'+release.plan+'/'+digest(r.payload),signature:r.signature}),'PUBLISHER_SIGNATURE');if(kind==='t2-ready')assert.equal(r.payload.snapshot.digest,release.snapshotDigest);if(kind==='t2-rebuild')assert.equal(r.payload.result.executionDigest,release.executionDigest);if(kind==='t2-local')assert.deepEqual(r.payload.steps.map((s:any)=>({step:s.step,bodyStateSha256:s.bodyStateSha256,spikes:s.spikes})),readJSON('expected/steps.json').steps);}
 assert.equal(digest(readJSON('expected/steps.json')),release.expectedDigest,'EXPECTED_CHANGED');
 const snap=new T2Snapshot(root,release.binding,{file:root+'/'+manifest.snapshotFile,digest:release.snapshotDigest});
 for(const [fn,val]of [['ready',true],['isSealed',true],['active',false],['completedSteps',0],['presentCount',10419]])assert.equal(decode(ba,fn as string,snap.manifest.globals[fn as string]),val,'INITIAL_STATE');
 return {release,snap,root};}
export async function prepare(){const {release,snap}=await snapshot(),c=release.binding,dest='.cache/rebuilt',cfg=decode(ba,'config',snap.manifest.globals.config),bases=new Float64Array(10420),tokens=new Map<string,number>();
 for(let i=0;i<10419;i++){const r=snap.get('slots',i),s=decode(ba,'slotSpec',r.encoded.slotSpec),h=decode(ba,'holding',r.encoded.holding);assert.equal(String(h.tokenId),r.tokenId);assert.equal(h.depositor.toLowerCase(),release.publisher.toLowerCase());assert.equal(decode(ca,'ownerOf',r.encoded.owner).toLowerCase(),c.brain.toLowerCase());assert.equal(Number(decode(ba,'occupiedToken',r.encoded.occupied)),i+1);assert.equal(decode(ca,'netlist',r.encoded.netlist),compileMicroCore().netlist);assert.ok(!tokens.has(r.tokenId));tokens.set(r.tokenId,i);bases[i+1]=bases[i]+s.edgeCounts.reduce((a:number,b:number)=>a+b,0)*8;}
 const connectionBytes=bases[10419],metadataBytes=6502144,connectionPages=Math.ceil(connectionBytes/4095);
 const pageConfig=readJSON('deployments/bsc-testnet/page-config.json'),pageTree=new IncrementalMerkle(),pageAbi=parseAbiParameters('bytes32,uint256,(uint8 kind,uint64 offset,uint32 length,bytes32 contentHash,bytes32 codeHash)');
 for(let i=0;i<51567;i++){const r=snap.get('pages',i);assert.equal(r.index,i);assert.ok(/^0x00[0-9a-f]+$/i.test(r.code));const kind=i<connectionPages?0:1,offset=(kind===0?i:i-connectionPages)*4095,length=Math.min(4095,(kind===0?connectionBytes:metadataBytes)-offset);assert.equal(r.code.length/2-2,length,'PAGE_PAYLOAD_LENGTH');const spec={kind,offset:BigInt(offset),length,contentHash:keccak256(('0x'+r.code.slice(4)) as any),codeHash:keccak256(r.code)};pageTree.append(keccak256(encodeAbiParameters(pageAbi,[pageConfig.binding,BigInt(i),spec])));}
 assert.equal(pageTree.finish(),pageConfig.pageRoot,'PAGE_ROOT');
 const bytes=(kind:string,offset:number,length:number)=>{assert.ok(length<=8192&&offset>=0&&offset+length<=(kind==='connection'?connectionBytes:metadataBytes));const out=Buffer.alloc(length);let done=0;while(done<length){const at=offset+done,index=(kind==='connection'?0:connectionPages)+Math.floor(at/4095),row=snap.get('pages',index),payload=Buffer.from(row.code.slice(4),'hex'),inner=at%4095,n=Math.min(length-done,payload.length-inner);assert.ok(n>0);payload.copy(out,done,inner,inner+n);done+=n;}return toHex(out);};
 const read=async(address:any,abi:any,fn:string,args:any[]=[]):Promise<any>=>{if(address.toLowerCase()===c.cpu.toLowerCase()){const slot=tokens.get(String(args[0]));assert.ok(slot!==undefined);assert.ok(['netlist','circuitInfo'].includes(fn));return decode(ca,fn,snap.get('slots',slot).encoded[fn]);}assert.equal(address.toLowerCase(),c.brain.toLowerCase());if(fn==='dataChunk'){const i=Number(args[0]);return bytes('metadata',i*8192,Math.min(8192,metadataBytes-i*8192));}if(fn==='edgeChunk'){const s=Number(args[0]),i=Number(args[1]);return bytes('connection',bases[s]+i*512,Math.min(512,bases[s+1]-bases[s]-i*512));}if(['slotSpec','holding','committedState','pendingState','currentWork'].includes(fn))return decode(ba,fn,snap.get('slots',Number(args[0])).encoded[fn]);const key=fn==='inputFrame'?fn+'/'+Number(args[0]):fn;assert.ok(snap.manifest.globals[key],'MISSING_CHAIN_FIELD');return decode(ba,fn,snap.manifest.globals[key]);};
 if(!fs.existsSync(dest)){await reconstructPackedMicroChain(read,c.brain,ba,ca,dest,{slotRoot:cfg[6],dataRoot:cfg[7],frameRoot:cfg[8],checkpointHash:await read(c.brain,ba,'checkpointHash'),microcheckpointHash:await read(c.brain,ba,'microcheckpointHash'),verifyBlock:async()=>{assert.equal(snap.manifest.binding.block.hash,release.binding.block.hash);}});}
 const loaded=loadMicroPlan(dest+'/execution',release.executionDigest),rt=new PackedMicroRuntime(loaded.plan,loaded.digest);rt.load(dest+'/checkpoint',release.checkpointDigest,release.stateDigest);assert.equal(rt.step,0);assert.equal(rt.active,false);assert.equal(rt.presentCount,10419);assert.equal((loaded.provenance as any).source.binding.datasetId,'male-cns:v1.0');assert.equal(digest((loaded.provenance as any).source.binding),digest(release.modelBinding));
 return {loaded,rt,release,snap,dest};}
